Add breakpad (symbol dumping) support
KDE/craft pull request #8
Opened 2018-09-22 11:43 UTC by dschmidt

2018-09-24 06:44 UTC, TheOneRing commented on CraftSettings.ini.template
> +Enabled = False
Just make it a setting in the Packager category

2018-09-24 06:54 UTC, TheOneRing requested changes

2018-09-24 06:54 UTC, TheOneRing commented on bin/Packager/CollectionPackagerBase.py
> +            if (not os.path.exists(outputPath)):
just use utils.createDirectory without a condition

2018-09-24 06:54 UTC, TheOneRing commented on blueprints/dev-utils/breakpad-tools/breakpad-tools.py
> +        self.buildDependencies["dev-utils/python2"] = "default"
also depend on virtual/base and use None instead of default

2018-09-24 06:54 UTC, TheOneRing commented on bin/info.py
> +            self.buildDependencies["dev-utils/breakpad-tools"] = "default"
None instead of default

2018-09-24 06:54 UTC, TheOneRing commented on bin/Packager/CollectionPackagerBase.py
> +        if not super().internalPostInstall():
We need to move this to a class in a higher level. Not everyone is inheriting CollectionPackagerBase.
Mybe just use PackagerBase?

2018-09-24 06:54 UTC, TheOneRing commented on bin/Packager/CollectionPackagerBase.py
> +            for entry in self.traverse(self.imageDir(), self.whitelisted, self.blacklisted):
We probably won't have a black or white list at the point we execute this code.
Please use os.walk for now or something similar

2019-11-08 09:59 UTC, TheOneRing commented
Solved in https://github.com/owncloud/craft-blueprints-owncloud

2019-11-08 09:59 UTC, closed without merging

2019-11-11 10:26 UTC, dschmidt commented
It isn't but I won't fight over this as Sentry has native .pdb and .dSYM support.

FTR; This PR was about adding breakpad symbol dumping to all packages, so we don't keep dumping Qt symbols (e.g.) over and over again when we actually just would need to dump the new build client symbols. That's why I wanted to bring this to the core ...