WIP: Add macOS pkg packaging and signing
KDE/craft pull request #9
Opened 2018-09-25 19:51 UTC by dschmidt

I'm not happy with the code: having ifs everywhere sprinkled around the Packager is really poor from a OOP POV. 

We should probably split this into different classes - just wanted to show off what's needed, so we can discuss the architecture better.

2018-09-26 06:28 UTC, TheOneRing requested changes

2018-09-26 06:28 UTC, TheOneRing commented on bin/utils.py
> +    if not system("security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k \"%s\" ~/Library/Keychains/login.keychain" % password, stdout=subprocess.DEVNULL, logCommand=False):
don't use %s strings

2018-09-26 06:28 UTC, TheOneRing commented on bin/utils.py
> +        packagePathTmp = "%s.sign" % packagePath
use format string or literal f"{foo}"

2018-09-26 06:28 UTC, TheOneRing commented on bin/Packager/MacDMGPackager.py
> +            if self.packageSubType() == "dmg":
I know they share 90% of the code but can you use the typepackager and a new common class  instead of introducing a new setting.
So a shared base class that creates a clean .app folder and two packager one for pkg and one for dmg

2018-09-26 06:28 UTC, TheOneRing commented on bin/utils.py
> +    if os.path.isdir(fileName):
move one line up or combine with islink

2018-09-26 07:56 UTC, dschmidt commented on bin/Packager/MacDMGPackager.py
> +            if self.packageSubType() == "dmg":
Have you read a) the commit message b) the PR description text?

2019-05-12 11:03 UTC, Inokinoki commented on bin/Packager/MacDMGPackager.py
> +            if self.packageSubType() == "dmg":
> I know they share 90% of the code but can you use the typepackager and a new common class instead of introducing a new setting.
> So a shared base class that creates a clean .app folder and two packager one for pkg and one for dmg

Yes, I think it's better than this solution.
But as the PR is just a POC, we could simply get ideas from it.

2019-12-09 09:41 UTC, TheOneRing commented
Taking over from here

2019-12-09 09:41 UTC, closed without merging